### ISSUE TITLE
Language Button in Sugarizer website shows a broken image

### ISSUE THREAD

**Issue by AndreaGon** [llaske/sugarizer-doc#21]
The language image shows a broken image when there are no current language: 

![bug1](https://user-images.githubusercontent.com/44361130/54250809-317e4500-4580-11e9-8ea6-e47542d7248e.PNG)

This is what shows on my computer when I visit Sugarizer website. If I choose a language, only then will the flag image appear.

**Comment by llaske** [comment]
What's your browser/environment? Do you have any message in the console?

**Comment by AndreaGon** [comment]
I tested it on Firefox, Chrome and Microsoft Edge on Windows 10. Both Firefox, Chrome, and Microsoft Edge  gave a warning sign that says "#snapcraft is undefined" on the console. Also, Chrome and Microsoft edge gives off a 404 not found error:

Chrome: 
`Failed to load resource: the server responded with a status of 404 (Not Found)           en.svg:1`

Microsoft Edge:
```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://sugarizer.org/img/en.svg
```

**Comment by llaske** [comment]
Ok thanks. Fixed in https://github.com/llaske/Sugarizer_doc/commit/9490fab0325379dba8553545937562693ea34083
