### ISSUE TITLE
Update Demo of Enhanced activities

### ISSUE THREAD

**Issue by saurabhhere** [llaske/sugarizer-doc#26]
New Buttons are added in Clock Activity but still, the old gif is present in the Demo.

If this issue looks good to you, I will update the new gif :)

**Comment by llaske** [comment]
Sure the GIF is an older one. Could be nice to integrate new features.
You deserve to do it :smile: 
Please suggest a new one.

**Comment by saurabhhere** [comment]
Thanks :smile:

I have made one GIF for the Clock Activity. Please have a look at it.

![clock](https://user-images.githubusercontent.com/60233336/117956583-cf275780-b336-11eb-88f4-2c4aae319a6c.gif)

Any other changes you want in GIF? Or should I submit a PR?

**Comment by llaske** [comment]
That's fine.
Just a small change at the beginning of the GIF: the Clock icon should be already colored so it's more easily identifiable.
