### ISSUE TITLE
Extra margin under sponsor button

### ISSUE THREAD

**Issue by rucha0702** [llaske/sugarizer-doc#28]
There is an extra margin under the sponsor button that could be removed. The button looks good if the border-radius is removed instead too.

Before:
![image](https://user-images.githubusercontent.com/77936051/149621475-6e75d086-d671-4399-aa15-57f143b4db83.png)
After:
![image](https://user-images.githubusercontent.com/77936051/149621435-49dd80dc-82f9-4950-a875-2424092cd2f1.png)

I would like to work on this issue if approved.

**Comment by llaske** [comment]
Thanks for your proposal.
But interesting, it seems that it's specific to Chrome.

On Firefox:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/981841/149678895-5d82e930-ea7c-4f11-a8c9-44fabf1b89b9.png">

On Safari:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/981841/149678912-79d6b543-4c15-4342-bf87-8ca59e4e70b5.png">

On Chrome:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/981841/149678926-2c0735f6-90b4-4520-9d2b-7d39138d3bd1.png">

You could work on it but be careful to the compatibility.

**Comment by rucha0702** [comment]
Okay, I'll try to make it look like the one on Firefox and Safari.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-doc/commit/02601fb294b5554068248299758f35c37e1a7376
