### ISSUE TITLE
Alignment of Social Buttons

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-doc#31]
Hey @llaske , I noticed a irregularity in the styling of social buttons in the footer section of website.

I guess it should have a proper alignment.

<img width="423" alt="Screenshot 2023-03-13 at 11 49 05 PM" src="https://user-images.githubusercontent.com/75615092/224796530-cb3dad67-6544-4d46-870e-da10cbbc13bf.png">

**Comment by llaske** [comment]
Yes why not.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-doc/pull/33
