### ISSUE TITLE
Position of the Vertical Dots

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [llaske/sugarizer-doc#32]
Hey @llaske, I noticed that the vertical dots on the right side of screens overlaps on the content when opened on smaller screen.

I recommended if we could fix the alignment of text and wrap it in a container so it does not overflow or we could hide the vertical dots on smaller screen. It seems a better idea not to display dots for smaller screens and to show them on medium or larger devices.
 
<img width="423" alt="Screenshot 2023-03-13 at 11 51 22 PM" src="https://user-images.githubusercontent.com/75615092/224797457-8c47ba66-115a-4c26-a331-f716a7463014.png">

What do you think ?

**Comment by llaske** [comment]
Not, it's nice to have the menu there.

**Comment by ABHINAV-JHA-27** [comment]
Hi @llaske ,  I too fell its good to have it here and it gives a good look.
I was just wondering. if we could just manage the text content over here so it doe not gets hidden.
What do you say ?

**Comment by llaske** [comment]
No it's good like that.
