### ISSUE TITLE
Buttons not working in Explore all activities section

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer-doc#35]
Hi @llaske,

I found that only the +4 option was working in explore all activities page, rest are not working and the no. of rows per page is also not working

Not working
![Screenshot 2023-09-01 090842](https://github.com/llaske/sugarizer-doc/assets/116670999/114f7430-22de-4726-a2e5-7ef17e7938c3)

Working only in +4
![Screenshot 2023-09-01 090922](https://github.com/llaske/sugarizer-doc/assets/116670999/2fc29c95-b857-45e2-a8b8-3978aca4a9d3)

**Comment by llaske** [comment]
Hmmm. Everything works on my side.

![CWk9TCMpFh](https://github.com/llaske/sugarizer-doc/assets/981841/7010a16d-ea53-4a0a-9684-5b2c4238819d)

Do you have any message in the console?

**Comment by Vishalk91-4** [comment]
@llaske, my point was like if you clikck+4 then only +4 is displayed but if you click +6 or +8 or +11, we see mixed things like +4, +6, +8 all

**Comment by llaske** [comment]
That's normal. It's to determine the age at which an activity can be used. If you can use an activity at 6, you can use at 4 (and so on).

**Comment by Vishalk91-4** [comment]
> That's normal. It's to determine the age at which an activity can be used. If you can use an activity at 6, you can use at 4 (and so on).

Sorry, I misinterpreted it, I thought it was specific like only +6 or +8 or +11
But another issue was that the page Rows per page dropdown is not working, can I work on that

**Comment by llaske** [comment]
> But another issue was that the page Rows per page dropdown is not working, can I work on that

Sure. But open another issue.
