### ISSUE TITLE
Sort By displays no options in mobile version

### ISSUE THREAD

**Issue by Vishalk91-4** [llaske/sugarizer-doc#40]
Hi @llaske 
In the mobile version, we can see that there are no option being displayed for sort by, even though if we click anyone of them, it sorts the order 
Same ways in desktop version also, we see the arrow only if we hover above the top activity on the left side

![image](https://github.com/llaske/sugarizer-doc/assets/116670999/1960c43a-72d6-4e14-936e-c1513a660eb2)

**Comment by llaske** [comment]
That's right.
