### ISSUE TITLE
Outdated X ( twitter ) icon 

### ISSUE THREAD

**Issue by HitanshuPrasad** [llaske/sugarizer-doc#46]
In footer , the X icon is outdated.

**Comment by HitanshuPrasad** [comment]
I am working on this but the current font awesome files used does not have updated version.  Should whole files be updated to latest or the new logo added as a svg?

**Comment by llaske** [comment]
> I am working on this but the current font awesome files used does not have updated version. Should whole files be updated to latest or the new logo added as a svg?

It's better to update the whole file is there is an updated version of awesome files.

**Comment by HitanshuPrasad** [comment]
I have updated the files for font -awesome. Review the PR for the changes, if it looks fine.
