### ISSUE TITLE
Update Year in footer

### ISSUE THREAD

**Issue by samyakshah3008** [llaske/sugarizer-doc#52]
### Description: 

- In the footer of a few pages of `get started` section, -- first step, hometoclass and journel, the year timeline shows: 2013 to 2022. 
To keep our website updated, we should update the year to 2023. 

Links: 

- https://sugarizer.org/docs/articles/hometoclass_en.html
- https://sugarizer.org/docs/articles/firststep_en.html
- https://sugarizer.org/docs/articles/journal_en.html 

All same links for _fr.html too.

**Comment by llaske** [comment]
In copyright law only the year of first publication of the work is need, so it's not a requirement to change it each year.
Plus, as mentioned in a comment in the beginning of all HTML files, articles are generated from the MD files so it has no sense to update them.

**Comment by samyakshah3008** [comment]
Cool, all looks good then to close this issue. 

I was going through the website and found the year 2022, so thought we can update it 😄 now got it.
